### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SandraMadarnas** [4GeeksAcademy/2-Random-Card-Generator-Raul-Gimenez#1]
Feedback de Adrián:

¡Muy buen trabajo! Enhorabuena por haber conseguido contabilizar las cartas que se van “gastando”. Único comentario: no sé el efecto que buscabas con el hover pero ha quedado un poco raro sweat_smile

Yo revisaría eso, pero no hace falta que reentregues porque el trabajo está perfect.

---------------------------------------------------------------------------------------------------

Feedback de Sandra:

¡Buen trabajo, Raúl! Esta muuuuuy genial. Me ha gustado mucho, sólo no abuses mucho del hover del resto está de 10! Te felicito, estoy deseando ver más proyectos tuyos!!!

**Comment by Raauul1996** [comment]
Gracias a los dos! Mi intención con el hover era que la carta se diera la vuelta, para al hacer click en ella el cambio de carta "no se viese" y ver solo el dorso de la carta.
